training_pipeline_config:
  pipeline_name: ml
  artifact_dir: artifact

data_ingestion_config:
  dataset_download_url: https://raw.githubusercontent.com/chandanc5525/cement_strength_prediction_model/main/concrete.csv
  raw_data_dir: raw_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test
